### ISSUE TITLE
Support a unbundled Version within the npm repositories

### ISSUE THREAD

**Issue by quorak** [MarshallOfSound/react-electron-web-view#7]
hey, would be great to support this unbundled, so i can pack it more efficently with webpack and the rest of my code:
```
./~/react-electron-web-view/lib/ElectronWebView.js
Critical dependencies:
1:488-495 This seems to be a pre-built javascript file. Though this is possible, it' s not recommended. Try to require the original source to get better results.
 @ ./~/react-electron-web-view/lib/ElectronWebView.js 1:488-495
```

thx a lot

**Comment by kengorab** [comment]
Yeah, the bundled file is *enormous*; it looks like it includes all of React within it! It'd be great to be able to pull in only the `<WebView>` component.

Another thing (and this may be better off as a separate issue), if the module didn't consist of the bundled and transpiled WebView class, we'd be able to import it properly when using ES6 imports (and, by extension, Typescript imports). As it stands right now, in order to import this using Typescript I need to do

```typescript
import * as WebView from 'react-electron-web-view';
```

but even that's "incorrect" as the "correct" approach would be to still use `require`. I noticed this while writing a Typescript type definitions file for this library, which I'll try to make available soon.

**Comment by agdolla** [comment]
@kengorab can you make the typescript definition available?

**Comment by mhuggins** [comment]
+1, was going to use this package, but I can't since it includes all of react.

**Comment by mhuggins** [comment]
It looks like there's an [external](https://github.com/browserify/browserify#bexternalfile) option for browserify, which is [explained in more detail here](https://stackoverflow.com/questions/29222745/how-do-i-exclude-the-requirereact-from-my-browserified-bundle)
